const users = [];

export const applicationsData = [
    {
      name: "Jo",
      image: "/img/user.png",
      title: "Junior Full-stack Developer (React.js + PHP)",
      skills: ["React.js", "PHP", "OOP", "Express.js", "Node.js", "HTMl", "JS"],
      career_level: "Junior",
      age: 20,
      address : "Cairo",
      status : "Pending"
    },
    {
      name: "Ahmed",
      image: "/img/user.png",
      title: "Junior Full-stack Developer (React.js + PHP)",
      skills: ["React.js", "PHP", "OOP", "Express.js", "Node.js", "HTMl", "JS"],
      career_level: "Junior",
      age: 20,
      address : "Cairo",
      status : "Pending"
    },
    {
      name: "Jo",
      image: "/img/user.png",
      title: "Junior Full-stack Developer (React.js + PHP)",
      skills: ["React.js", "PHP", "OOP", "Express.js", "Node.js", "HTMl", "JS"],
      career_level: "Junior",
      age: 20,
      address : "Cairo",
      status : "Pending"
    },
    {
      name: "Ahmed",
      image: "/img/user.png",
      title: "Junior Full-stack Developer (React.js + PHP)",
      skills: ["React.js", "PHP", "OOP", "Express.js", "Node.js", "HTMl", "JS"],
      career_level: "Junior",
      age: 20,
      address : "Cairo",
      status : "Pending"
    },
    {
      name: "Jo",
      image: "/img/user.png",
      title: "Junior Full-stack Developer (React.js + PHP)",
      skills: ["React.js", "PHP", "OOP", "Express.js", "Node.js", "HTMl", "JS"],
      career_level: "Junior",
      age: 20,
      address : "Cairo",
      status : "Pending"
    },
    {
      name: "Ahmed",
      image: "/img/user.png",
      title: "Junior Full-stack Developer (React.js + PHP)",
      skills: ["React.js", "PHP", "OOP", "Express.js", "Node.js", "HTMl", "JS"],
      career_level: "Junior",
      age: 20,
      address : "Cairo",
      status : "Pending"
    },
    {
      name: "Jo",
      image: "/img/user.png",
      title: "Junior Full-stack Developer (React.js + PHP)",
      skills: ["React.js", "PHP", "OOP", "Express.js", "Node.js", "HTMl", "JS"],
      career_level: "Junior",
      age: 20,
      address : "Cairo",
      status : "Pending"
    },
    {
      name: "Ahmed",
      image: "/img/user.png",
      title: "Junior Full-stack Developer (React.js + PHP)",
      skills: ["React.js", "PHP", "OOP", "Express.js", "Node.js", "HTMl", "JS"],
      career_level: "Junior",
      age: 20,
      address : "Cairo",
      status : "Pending"
    },
    {
      name: "Jo",
      image: "/img/user.png",
      title: "Junior Full-stack Developer (React.js + PHP)",
      skills: ["React.js", "PHP", "OOP", "Express.js", "Node.js", "HTMl", "JS"],
      career_level: "Junior",
      age: 20,
      address : "Cairo",
      status : "Pending"
    },
    {
      name: "Ahmed",
      image: "/img/user.png",
      title: "Junior Full-stack Developer (React.js + PHP)",
      skills: ["React.js", "PHP", "OOP", "Express.js", "Node.js", "HTMl", "JS"],
      career_level: "Junior",
      age: 20,
      address : "Cairo",
      status : "Pending"
    },
    {
      name: "Jo",
      image: "/img/user.png",
      title: "Junior Full-stack Developer (React.js + PHP)",
      skills: ["React.js", "PHP", "OOP", "Express.js", "Node.js", "HTMl", "JS"],
      career_level: "Junior",
      age: 20,
      address : "Cairo",
      status : "Pending"
    },
    {
      name: "Ahmed",
      image: "/img/user.png",
      title: "Junior Full-stack Developer (React.js + PHP)",
      skills: ["React.js", "PHP", "OOP", "Express.js", "Node.js", "HTMl", "JS"],
      career_level: "Junior",
      age: 20,
      address : "Cairo",
      status : "Pending"
    },
  ];

export const jobsData = [
    {
      name: "Jo",
      image: "/img/user.png",
      title: "Junior Full-stack Developer (React.js + PHP)",
      skills: ["React.js", "PHP", "OOP", "Express.js", "Node.js", "HTMl", "JS"],
      career_level: "Junior",
      age: 20,
      address: "Cairo",
    },
    {
      name: "Ahmed",
      image: "/img/user.png",
      title: "Junior Full-stack Developer (React.js + PHP)",
      skills: ["React.js", "PHP", "OOP", "Express.js", "Node.js", "HTMl", "JS"],
      career_level: "Junior",
      age: 20,
      address: "Cairo",
    },
    {
      name: "Jo",
      image: "/img/user.png",
      title: "Junior Full-stack Developer (React.js + PHP)",
      skills: ["React.js", "PHP", "OOP", "Express.js", "Node.js", "HTMl", "JS"],
      career_level: "Junior",
      age: 20,
      address: "Cairo",
    },
    {
      name: "Ahmed",
      image: "/img/user.png",
      title: "Junior Full-stack Developer (React.js + PHP)",
      skills: ["React.js", "PHP", "OOP", "Express.js", "Node.js", "HTMl", "JS"],
      career_level: "Junior",
      age: 20,
      address: "Cairo",
    },
    {
      name: "Jo",
      image: "/img/user.png",
      title: "Junior Full-stack Developer (React.js + PHP)",
      skills: ["React.js", "PHP", "OOP", "Express.js", "Node.js", "HTMl", "JS"],
      career_level: "Junior",
      age: 20,
      address: "Cairo",
    },
    {
      name: "Ahmed",
      image: "/img/user.png",
      title: "Junior Full-stack Developer (React.js + PHP)",
      skills: ["React.js", "PHP", "OOP", "Express.js", "Node.js", "HTMl", "JS"],
      career_level: "Junior",
      age: 20,
      address: "Cairo",
    },
    {
      name: "Jo",
      image: "/img/user.png",
      title: "Junior Full-stack Developer (React.js + PHP)",
      skills: ["React.js", "PHP", "OOP", "Express.js", "Node.js", "HTMl", "JS"],
      career_level: "Junior",
      age: 20,
      address: "Cairo",
    },
    {
      name: "Ahmed",
      image: "/img/user.png",
      title: "Junior Full-stack Developer (React.js + PHP)",
      skills: ["React.js", "PHP", "OOP", "Express.js", "Node.js", "HTMl", "JS"],
      career_level: "Junior",
      age: 20,
      address: "Cairo",
    },
    {
      name: "Jo",
      image: "/img/user.png",
      title: "Junior Full-stack Developer (React.js + PHP)",
      skills: ["React.js", "PHP", "OOP", "Express.js", "Node.js", "HTMl", "JS"],
      career_level: "Junior",
      age: 20,
      address: "Cairo",
    },
    {
      name: "Ahmed",
      image: "/img/user.png",
      title: "Junior Full-stack Developer (React.js + PHP)",
      skills: ["React.js", "PHP", "OOP", "Express.js", "Node.js", "HTMl", "JS"],
      career_level: "Junior",
      age: 20,
      address: "Cairo",
    },
    {
      name: "Jo",
      image: "/img/user.png",
      title: "Junior Full-stack Developer (React.js + PHP)",
      skills: ["React.js", "PHP", "OOP", "Express.js", "Node.js", "HTMl", "JS"],
      career_level: "Junior",
      age: 20,
      address: "Cairo",
    },
    {
      name: "Ahmed",
      image: "/img/user.png",
      title: "Junior Full-stack Developer (React.js + PHP)",
      skills: ["React.js", "PHP", "OOP", "Express.js", "Node.js", "HTMl", "JS"],
      career_level: "Junior",
      age: 20,
      address: "Cairo",
    },
  ];